server:
  port: 9099
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ANILMAJHI/BootRestDoctorDB-configrepo.git
          default-label: master
  application:
    name: patient-mangt-service
